//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JiGuangLinXin.App.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Core_VoucherCard
    {
        public System.Guid C_Id { get; set; }
        public string C_Title { get; set; }
        public Nullable<System.Guid> C_BusId { get; set; }
        public string C_BusNickname { get; set; }
        public string C_BusPhone { get; set; }
        public decimal C_Money { get; set; }
        public string C_Remark { get; set; }
        public System.DateTime C_STime { get; set; }
        public System.DateTime C_ETime { get; set; }
        public System.DateTime C_Time { get; set; }
        public int C_State { get; set; }
    }
}
