//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JiGuangLinXin.App.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Core_AuditingCash
    {
        public System.Guid M_Id { get; set; }
        public System.Guid M_UId { get; set; }
        public string M_Bank { get; set; }
        public string M_BankAddress { get; set; }
        public string M_BankAccount { get; set; }
        public string M_BankName { get; set; }
        public decimal M_Money { get; set; }
        public string M_Phone { get; set; }
        public string M_Remark { get; set; }
        public System.DateTime M_Time { get; set; }
        public int M_Status { get; set; }
        public string M_CheckBack { get; set; }
        public Nullable<System.DateTime> M_CheckTime { get; set; }
        public int M_Flag { get; set; }
        public int M_Role { get; set; }
    }
}
