//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JiGuangLinXin.App.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Core_EventJoinHistory
    {
        public System.Guid H_Id { get; set; }
        public System.Guid H_EventId { get; set; }
        public string H_EventTtitle { get; set; }
        public Nullable<System.Guid> H_UserId { get; set; }
        public string H_UserName { get; set; }
        public string H_Remark { get; set; }
        public Nullable<System.Guid> H_VoteId { get; set; }
        public string H_VoteTitle { get; set; }
        public int H_Flag { get; set; }
        public System.DateTime H_Time { get; set; }
    }
}
