//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JiGuangLinXin.App.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Core_BusinessVillage
    {
        public int BV_Id { get; set; }
        public System.Guid BV_BusinessId { get; set; }
        public System.Guid BV_VillageId { get; set; }
        public System.DateTime BV_Date { get; set; }
        public string BV_CityName { get; set; }
        public string BV_DistrictName { get; set; }
        public string BV_BuildingName { get; set; }
    }
}
