//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JiGuangLinXin.App.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Core_GroupAlbumPic
    {
        public System.Guid P_Id { get; set; }
        public Nullable<System.Guid> P_AlbumId { get; set; }
        public System.Guid P_BuildingId { get; set; }
        public string P_BuildingName { get; set; }
        public string P_Title { get; set; }
        public string P_Desc { get; set; }
        public Nullable<System.Guid> P_UId { get; set; }
        public string P_UName { get; set; }
        public int P_State { get; set; }
        public int P_Rank { get; set; }
        public string P_FileNameOld { get; set; }
        public string P_FileName { get; set; }
        public double P_Size { get; set; }
        public Nullable<System.DateTime> P_Time { get; set; }
        public string P_Folder { get; set; }
        public string P_AreaCode { get; set; }
        public string P_City { get; set; }
    }
}
