//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JiGuangLinXin.App.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Core_Balance
    {
        public System.Guid B_AccountId { get; set; }
        public decimal B_Balance { get; set; }
        public decimal B_ForzenMoney { get; set; }
        public decimal B_CouponMoney { get; set; }
        public byte[] B_Vesion { get; set; }
        public string B_PayPwd { get; set; }
        public string B_EncryptCode { get; set; }
        public int B_Role { get; set; }
    }
}
