//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JiGuangLinXin.App.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Core_Feedback
    {
        public int F_Id { get; set; }
        public System.Guid F_UId { get; set; }
        public string F_Phone { get; set; }
        public string F_Title { get; set; }
        public string F_Content { get; set; }
        public string F_Reply { get; set; }
        public int F_Status { get; set; }
        public System.DateTime F_Time { get; set; }
        public Nullable<System.DateTime> F_ReplyTime { get; set; }
        public int F_Flag { get; set; }
    }
}
