//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JiGuangLinXin.App.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Core_ActivityGoods
    {
        public int AG_Id { get; set; }
        public System.Guid AG_ActivityId { get; set; }
        public string AG_Name { get; set; }
        public string AG_Img { get; set; }
        public decimal AG_Price { get; set; }
        public int AG_Store { get; set; }
        public int AG_RemainCount { get; set; }
        public int AG_Status { get; set; }
        public System.DateTime AG_Time { get; set; }
        public string AG_Remark { get; set; }
        public byte[] AG_Vesion { get; set; }
    }
}
