//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JiGuangLinXin.App.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Core_ChinapayOrder_bk
    {
        public System.Guid C_Id { get; set; }
        public string C_ResponseCode { get; set; }
        public string C_ResponseDesc { get; set; }
        public string C_ReqSeqId { get; set; }
        public string C_ReqTransDate { get; set; }
        public string C_BranchId { get; set; }
        public string C_ResSeqId { get; set; }
        public string C_ResTransDate { get; set; }
        public string C_OrdId { get; set; }
        public string C_OrdDate { get; set; }
        public string C_OrdStat { get; set; }
        public string C_UserId { get; set; }
        public string C_MerSysId { get; set; }
        public string C_MerId { get; set; }
        public string C_BillNo { get; set; }
        public string C_BillDate { get; set; }
        public string C_MerAccount { get; set; }
        public string C_BillAmt { get; set; }
        public string C_ScBillStat { get; set; }
        public string C_IndividualArea { get; set; }
        public string C_Resv2 { get; set; }
        public string C_Resv4 { get; set; }
        public string C_Resv3 { get; set; }
        public string C_Resv1 { get; set; }
        public string C_BillInfo { get; set; }
        public int C_Status { get; set; }
        public string C_Resv { get; set; }
    }
}
