//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JiGuangLinXin.App.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Core_ScoreExchange
    {
        public int E_Id { get; set; }
        public System.Guid E_UId { get; set; }
        public string E_Phone { get; set; }
        public int E_Role { get; set; }
        public Nullable<System.Guid> E_BuildingId { get; set; }
        public string E_BuildingName { get; set; }
        public int E_Module { get; set; }
        public string E_OrderNo { get; set; }
        public string E_Title { get; set; }
        public int E_Score { get; set; }
        public string E_Remark { get; set; }
        public System.DateTime E_Time { get; set; }
        public int E_Status { get; set; }
        public int E_Flag { get; set; }
    }
}
