//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JiGuangLinXin.App.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Core_Building
    {
        public System.Guid B_Id { get; set; }
        public System.Guid B_AdminId { get; set; }
        public string B_BusPhone { get; set; }
        public string B_BusName { get; set; }
        public string B_Name { get; set; }
        public string B_CityName { get; set; }
        public string B_DistrictName { get; set; }
        public int B_CellsCount { get; set; }
        public string B_Rooms { get; set; }
        public string B_Area { get; set; }
        public string B_Price { get; set; }
        public string B_Tags { get; set; }
        public string B_CovereImg { get; set; }
        public string B_Logo { get; set; }
        public string B_ImgTop { get; set; }
        public string B_VideoImg { get; set; }
        public string B_Video { get; set; }
        public string B_Content { get; set; }
        public int B_Clicks { get; set; }
        public int B_Status { get; set; }
        public int B_Flag { get; set; }
        public int B_IsHot { get; set; }
        public int B_IsThrift { get; set; }
        public int B_IsNew { get; set; }
        public int B_Recom { get; set; }
        public int B_Top { get; set; }
        public string B_Desc { get; set; }
        public string B_Address { get; set; }
        public string B_TargetCity { get; set; }
        public System.DateTime B_Time { get; set; }
        public string B_AdTitle { get; set; }
        public string B_AdBgImg { get; set; }
        public string B_AdCartoonImg { get; set; }
        public string B_AdUrl { get; set; }
        public int B_HongbaoCount { get; set; }
        public int B_HongbaoRemain { get; set; }
        public string B_HongbaoTips { get; set; }
        public decimal B_HongbaoMoney { get; set; }
        public System.DateTime B_BTime { get; set; }
        public System.DateTime B_ETime { get; set; }
        public string B_ActivityImg { get; set; }
        public string B_ActivityTitle { get; set; }
        public string B_ActivityContent { get; set; }
        public byte[] B_Timestamp { get; set; }
    }
}
