//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JiGuangLinXin.App.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Core_BusDeveloper
    {
        public System.Guid D_Id { get; set; }
        public string D_Name { get; set; }
        public string D_Logo { get; set; }
        public string D_Remark { get; set; }
        public string D_Address { get; set; }
        public string D_LinkMan { get; set; }
        public string D_LinkPhone { get; set; }
    }
}
