//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JiGuangLinXin.App.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Core_Prize
    {
        public System.Guid P_Id { get; set; }
        public int P_TypeId { get; set; }
        public System.Guid P_UId { get; set; }
        public string P_UPhone { get; set; }
        public int P_Count { get; set; }
        public int P_RemainCount { get; set; }
        public System.DateTime P_Time { get; set; }
        public System.DateTime P_TimeUseful { get; set; }
    }
}
