//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JiGuangLinXin.App.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Core_JuheOrder
    {
        public System.Guid O_Id { get; set; }
        public string O_OrderNo { get; set; }
        public System.Guid O_UId { get; set; }
        public string O_Phone { get; set; }
        public decimal O_Money { get; set; }
        public int O_Type { get; set; }
        public System.DateTime O_Time { get; set; }
        public int O_Status { get; set; }
        public string O_Remark { get; set; }
        public string O_PayUnitName { get; set; }
        public string O_Account { get; set; }
        public int O_DeptId { get; set; }
        public string O_DeptProjectName { get; set; }
    }
}
