//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JiGuangLinXin.App.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Core_GroupBuyScope
    {
        public System.Guid GS_Id { get; set; }
        public System.Guid GS_GId { get; set; }
        public System.Guid GS_BuildingId { get; set; }
        public System.DateTime GS_Time { get; set; }
        public string GS_CityName { get; set; }
        public string GS_DistrictName { get; set; }
        public string GS_BuildingName { get; set; }
    }
}
