//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JiGuangLinXin.App.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Core_GroupBuyOrder
    {
        public System.Guid BO_Id { get; set; }
        public System.Guid BO_UId { get; set; }
        public string BO_ULogo { get; set; }
        public string BO_UPhone { get; set; }
        public System.Guid BO_BuildignId { get; set; }
        public System.Guid BO_BusId { get; set; }
        public string BO_BusPhone { get; set; }
        public string BO_BusName { get; set; }
        public string BO_OrderNo { get; set; }
        public string BO_TargetName { get; set; }
        public decimal BO_Price { get; set; }
        public string BO_Titlte { get; set; }
        public string BO_CoverImg { get; set; }
        public string BO_TargetPhone { get; set; }
        public string BO_TargetAddress { get; set; }
        public int BO_PayState { get; set; }
        public int BO_OrderState { get; set; }
        public int BO_GoodsCount { get; set; }
        public decimal BO_OwnerCardMoney { get; set; }
        public string BO_Remark { get; set; }
        public System.DateTime BO_Time { get; set; }
        public System.Guid BO_GroupBuyId { get; set; }
        public System.DateTime BO_STime { get; set; }
        public System.DateTime BO_ETime { get; set; }
        public int BO_PeopleCount { get; set; }
    }
}
