//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JiGuangLinXin.App.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Core_Activity
    {
        public System.Guid A_Id { get; set; }
        public System.Guid A_BusinessId { get; set; }
        public string A_Logo { get; set; }
        public string A_Images { get; set; }
        public string A_Title { get; set; }
        public string A_Content { get; set; }
        public System.DateTime A_STime { get; set; }
        public System.DateTime A_ETime { get; set; }
        public int A_Clicks { get; set; }
        public int A_Type { get; set; }
        public int A_Sort { get; set; }
        public int A_Top { get; set; }
        public int A_Show { get; set; }
        public int A_Status { get; set; }
        public System.DateTime A_Time { get; set; }
        public string A_Desc { get; set; }
    }
}
