//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JiGuangLinXin.App.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Core_GroupAlbum
    {
        public System.Guid A_Id { get; set; }
        public System.Guid A_BuildingId { get; set; }
        public string A_BuildingName { get; set; }
        public string A_Title { get; set; }
        public string A_Desc { get; set; }
        public string A_CoverImg { get; set; }
        public int A_Count { get; set; }
        public Nullable<System.Guid> A_UId { get; set; }
        public string A_UName { get; set; }
        public int A_State { get; set; }
        public int A_Rank { get; set; }
        public System.DateTime A_Time { get; set; }
        public int A_Flag { get; set; }
    }
}
