//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JiGuangLinXin.App.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Core_JuheDept
    {
        public int D_Id { get; set; }
        public string D_ProvinceID { get; set; }
        public string D_ProvinceName { get; set; }
        public string D_CityID { get; set; }
        public string D_CityName { get; set; }
        public string D_ProjectID { get; set; }
        public string D_ProjectName { get; set; }
        public string D_UnitID { get; set; }
        public string D_UnitName { get; set; }
        public string D_ProductId { get; set; }
        public string D_ProductName { get; set; }
    }
}
