//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JiGuangLinXin.App.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Core_LuckyGiftBackOrder
    {
        public System.Guid BO_Id { get; set; }
        public System.Guid BO_GiftId { get; set; }
        public System.Guid BO_UId { get; set; }
        public decimal BO_Money { get; set; }
        public string BO_Remark { get; set; }
        public System.DateTime BO_Time { get; set; }
        public int BO_Status { get; set; }
        public string BO_UPhone { get; set; }
    }
}
