//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JiGuangLinXin.App.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Core_InviteGroup
    {
        public int G_Id { get; set; }
        public string G_Title { get; set; }
        public string G_Img { get; set; }
        public int G_Sort { get; set; }
        public string G_Tag { get; set; }
        public int G_Status { get; set; }
    }
}
