//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JiGuangLinXin.App.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Core_Business
    {
        public System.Guid B_Id { get; set; }
        public string B_LoginPhone { get; set; }
        public string B_LoginPwd { get; set; }
        public string B_PwdCode { get; set; }
        public int B_Role { get; set; }
        public string B_NickName { get; set; }
        public int B_Sex { get; set; }
        public string B_Birthday { get; set; }
        public int B_Age { get; set; }
        public string B_Logo { get; set; }
        public string B_Signatures { get; set; }
        public int B_RegisterSource { get; set; }
        public int B_AuditingState { get; set; }
        public int B_Status { get; set; }
        public string B_Desc { get; set; }
        public string B_Remark { get; set; }
        public string B_Phone { get; set; }
        public int B_Level { get; set; }
        public int B_VillageCount { get; set; }
        public string B_AreaCode { get; set; }
        public string B_City { get; set; }
        public string B_Address { get; set; }
        public System.DateTime B_RegisterDate { get; set; }
        public string B_ServiceImg { get; set; }
        public string B_ServiceItem { get; set; }
        public int B_Category { get; set; }
        public int B_IsFamous { get; set; }
        public int B_IsFree { get; set; }
        public int B_IsReturns { get; set; }
        public int B_IsHot { get; set; }
        public int B_IsAuthentic { get; set; }
        public string B_TrueName { get; set; }
        public string B_CardId { get; set; }
    }
}
