//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JiGuangLinXin.App.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Core_ChinapayOrder
    {
        public System.Guid D_Id { get; set; }
        public string A_MerSysId { get; set; }
        public string A_queryNo { get; set; }
        public string A_billType { get; set; }
        public string A_merBillStat { get; set; }
        public string A_billDate { get; set; }
        public string A_password { get; set; }
        public string A_individualArea { get; set; }
        public string A_writeOffType { get; set; }
        public string B_responseCode { get; set; }
        public string B_responseDesc { get; set; }
        public string B_billNo { get; set; }
        public string B_billAmt { get; set; }
        public string B_billDate { get; set; }
        public string B_merBillStat { get; set; }
        public string B_recordTimes { get; set; }
        public string B_individualArea { get; set; }
        public string B_reqSeqId { get; set; }
        public string B_reqTransDate { get; set; }
        public string B_userId { get; set; }
        public string B_writeOffType { get; set; }
        public string C_responseCode { get; set; }
        public string C_responseDesc { get; set; }
        public string C_reqSeqId { get; set; }
        public string C_reqTransDate { get; set; }
        public string C_branchId { get; set; }
        public string C_resSeqId { get; set; }
        public string C_resTransDate { get; set; }
        public string C_ordId { get; set; }
        public string C_ordDate { get; set; }
        public string C_ordStat { get; set; }
        public string C_userId { get; set; }
        public string C_resv1 { get; set; }
        public string C_merSysId { get; set; }
        public string C_merId { get; set; }
        public string C_billNo { get; set; }
        public string C_billAmt { get; set; }
        public string C_billDate { get; set; }
        public string C_merAccount { get; set; }
        public string C_scBillStat { get; set; }
        public string C_CuryId { get; set; }
        public string C_TransAmt { get; set; }
        public string C_RespCode { get; set; }
        public string C_BillInfo { get; set; }
        public string C_BankDate { get; set; }
        public string C_BankSeq { get; set; }
        public string C_Resv { get; set; }
        public string D_Resv { get; set; }
        public string D_Remark { get; set; }
        public string D_scBillStat { get; set; }
        public string D_ordStat { get; set; }
        public string D_billDate { get; set; }
        public int D_DeptId { get; set; }
        public string D_DeptName { get; set; }
        public string D_ProjectName { get; set; }
        public string D_PayBillId { get; set; }
        public System.Guid D_UserId { get; set; }
        public string D_UserPhone { get; set; }
        public System.DateTime D_Time { get; set; }
    }
}
