//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JiGuangLinXin.App.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Core_GroupBuyVillage
    {
        public System.Guid VB_Id { get; set; }
        public System.Guid VB_BuildingId { get; set; }
        public string VB_BuildignName { get; set; }
        public System.Guid VB_GroupBuyId { get; set; }
        public int VB_PeopleCount { get; set; }
        public int VB_JoinCount { get; set; }
        public int VB_State { get; set; }
        public System.DateTime VB_Time { get; set; }
        public System.DateTime VB_STime { get; set; }
        public System.DateTime VB_ETime { get; set; }
    }
}
