//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JiGuangLinXin.App.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Core_EventVoteItem
    {
        public System.Guid I_Id { get; set; }
        public System.Guid I_EventId { get; set; }
        public string I_EventTtitle { get; set; }
        public string I_Title { get; set; }
        public int I_Count { get; set; }
        public int I_Rank { get; set; }
        public byte[] I_Vesion { get; set; }
        public int I_State { get; set; }
        public string I_Img { get; set; }
        public string I_Remark { get; set; }
    }
}
