//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JiGuangLinXin.App.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Core_GroupBuyType
    {
        public int T_Id { get; set; }
        public string T_Title { get; set; }
        public string T_Remark { get; set; }
        public int T_Rank { get; set; }
        public int T_Recom { get; set; }
        public string T_CoverImg { get; set; }
        public string T_CoverImgRecom { get; set; }
        public int T_State { get; set; }
    }
}
