//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JiGuangLinXin.App.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Core_User
    {
        public System.Guid U_Id { get; set; }
        public string U_LoginPhone { get; set; }
        public string U_LoginPwd { get; set; }
        public string U_PwdCode { get; set; }
        public string U_ChatID { get; set; }
        public string U_TrueName { get; set; }
        public string U_NickName { get; set; }
        public int U_Sex { get; set; }
        public string U_Birthday { get; set; }
        public int U_Age { get; set; }
        public string U_Logo { get; set; }
        public string U_Signatures { get; set; }
        public int U_RegisterSource { get; set; }
        public double U_CoordX { get; set; }
        public double U_CoordY { get; set; }
        public System.Guid U_BuildingId { get; set; }
        public string U_BuildingName { get; set; }
        public int U_AuditingManager { get; set; }
        public int U_AuditingState { get; set; }
        public int U_BlockGroupMsg { get; set; }
        public int U_Status { get; set; }
        public System.DateTime U_RegisterDate { get; set; }
        public string U_AreaCode { get; set; }
        public string U_City { get; set; }
        public System.DateTime U_LastLoginTime { get; set; }
        public System.Data.Entity.Spatial.DbGeography U_Location { get; set; }
    }
}
