//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JiGuangLinXin.App.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Core_LuckyGift
    {
        public System.Guid LG_Id { get; set; }
        public string LG_Title { get; set; }
        public string LG_Tags { get; set; }
        public int LG_Type { get; set; }
        public System.Guid LG_UserId { get; set; }
        public string LG_UserNickname { get; set; }
        public Nullable<System.Guid> LG_ProjectId { get; set; }
        public string L_ProjectTitle { get; set; }
        public decimal LG_Money { get; set; }
        public decimal LG_RemainMoney { get; set; }
        public int LG_Count { get; set; }
        public int LG_RemainCount { get; set; }
        public System.DateTime LG_CreateTime { get; set; }
        public string LG_Remark { get; set; }
        public byte[] LG_Vesion { get; set; }
        public int LG_Status { get; set; }
        public string LG_AreaCode { get; set; }
        public System.Guid LG_VillageId { get; set; }
        public Nullable<System.Guid> LG_Flag { get; set; }
    }
}
