//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JiGuangLinXin.App.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Core_Invite
    {
        public System.Guid I_Id { get; set; }
        public System.Guid I_UId { get; set; }
        public string I_UPhone { get; set; }
        public int I_Group { get; set; }
        public string I_Title { get; set; }
        public string I_Content { get; set; }
        public int I_Type { get; set; }
        public int I_ApplyLimmit { get; set; }
        public int I_Apply { get; set; }
        public int I_Reply { get; set; }
        public int I_Clicks { get; set; }
        public int I_Recom { get; set; }
        public int I_Top { get; set; }
        public int I_Status { get; set; }
        public byte[] I_Vesion { get; set; }
        public System.DateTime I_Time { get; set; }
    }
}
