//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JiGuangLinXin.App.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Core_GroupBuy
    {
        public System.Guid GB_Id { get; set; }
        public System.Guid GB_BusId { get; set; }
        public string GB_BusName { get; set; }
        public string GB_BusPhone { get; set; }
        public string GB_CoverImg { get; set; }
        public int GB_LimitCount { get; set; }
        public int GB_PeopleCount { get; set; }
        public string GB_Titlte { get; set; }
        public string GB_Tags { get; set; }
        public int GB_State { get; set; }
        public System.DateTime GB_STime { get; set; }
        public System.DateTime GB_ETime { get; set; }
        public decimal GB_Price { get; set; }
        public decimal GB_PriceOld { get; set; }
        public int GB_Discount { get; set; }
        public string GB_Desc { get; set; }
        public decimal GB_ExtraFee { get; set; }
        public Nullable<int> GB_Sales { get; set; }
        public int GB_Clicks { get; set; }
        public byte[] GB_Vesion { get; set; }
        public string GB_Remark { get; set; }
        public System.DateTime GB_Time { get; set; }
        public string GB_CoverList { get; set; }
        public int GB_Top { get; set; }
        public int GB_AuditingState { get; set; }
        public int GB_TypeId { get; set; }
        public string GB_TypeName { get; set; }
        public Nullable<System.DateTime> GB_CheckTime { get; set; }
        public string GB_CheckTips { get; set; }
        public int GB_Target { get; set; }
    }
}
