//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JiGuangLinXin.App.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Core_PrizeDetail
    {
        public System.Guid PD_Id { get; set; }
        public System.Guid PD_UId { get; set; }
        public string PD_UPhone { get; set; }
        public string PD_Award { get; set; }
        public decimal PD_LuckGift { get; set; }
        public int PD_OwnerCard { get; set; }
        public int PD_Flag { get; set; }
        public double PD_Rate { get; set; }
        public System.DateTime PD_Time { get; set; }
        public System.DateTime PD_TimeUseful { get; set; }
        public int PD_Round { get; set; }
        public Nullable<System.DateTime> PD_TimeAward { get; set; }
        public int PD_TypeId { get; set; }
    }
}
