//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JiGuangLinXin.App.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Core_Billboard
    {
        public int B_Id { get; set; }
        public string B_Title { get; set; }
        public string B_Content { get; set; }
        public int B_Flag { get; set; }
        public string B_Tags { get; set; }
        public int B_Clicks { get; set; }
        public string B_Remark { get; set; }
        public int B_State { get; set; }
        public System.Guid B_BuildingId { get; set; }
        public string B_BuildingName { get; set; }
        public System.Guid B_UId { get; set; }
        public string B_UPhone { get; set; }
        public string B_NickName { get; set; }
        public System.DateTime B_Date { get; set; }
    }
}
