//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JiGuangLinXin.App.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Core_LuckyGiftHistory
    {
        public System.Guid LH_Id { get; set; }
        public System.Guid LH_UserId { get; set; }
        public string LH_UserNickName { get; set; }
        public string LH_UserPhone { get; set; }
        public System.Guid LH_GiftId { get; set; }
        public Nullable<System.Guid> LH_GiftDetailId { get; set; }
        public decimal LH_Money { get; set; }
        public System.DateTime LH_CreateTime { get; set; }
        public string LH_Remark { get; set; }
        public int LH_Status { get; set; }
        public int LH_Flag { get; set; }
        public string LH_UserLogo { get; set; }
    }
}
