//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JiGuangLinXin.App.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Core_Interactive
    {
        public System.Guid I_Id { get; set; }
        public System.Guid I_UserId { get; set; }
        public string I_UserName { get; set; }
        public string I_UserLogo { get; set; }
        public string I_Title { get; set; }
        public string I_Content { get; set; }
        public int I_Type { get; set; }
        public int I_Hongbao { get; set; }
        public string I_Img { get; set; }
        public string I_Tags { get; set; }
        public string I_Remark { get; set; }
        public int I_Clicks { get; set; }
        public int I_Likes { get; set; }
        public int I_Comments { get; set; }
        public int I_Recom { get; set; }
        public int I_Top { get; set; }
        public int I_Status { get; set; }
        public string I_AreaCode { get; set; }
        public System.Guid I_VillageId { get; set; }
        public System.DateTime I_Date { get; set; }
        public int I_Flag { get; set; }
        public int I_Tag { get; set; }
    }
}
