//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JiGuangLinXin.App.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Core_ActivityGoodsOrder
    {
        public int GO_Id { get; set; }
        public System.Guid GO_UId { get; set; }
        public string GO_UPhone { get; set; }
        public System.Guid GO_ActivityId { get; set; }
        public int GO_GoodsId { get; set; }
        public string GO_OrderNo { get; set; }
        public string GO_Name { get; set; }
        public string GO_Img { get; set; }
        public decimal GO_Price { get; set; }
        public string GO_TargetName { get; set; }
        public string GO_TargetPhone { get; set; }
        public string GO_TargetAddress { get; set; }
        public int GO_Status { get; set; }
        public System.DateTime GO_Time { get; set; }
        public string GO_Remark { get; set; }
    }
}
