//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JiGuangLinXin.App.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Core_ChinapayDept
    {
        public int D_Id { get; set; }
        public string D_CityName { get; set; }
        public int D_ProjectID { get; set; }
        public string D_ProjectName { get; set; }
        public string D_UnitName { get; set; }
        public string D_MerSysId { get; set; }
        public int D_BillPwd { get; set; }
        public int D_BillDate { get; set; }
        public string D_IndividualAreaQuery { get; set; }
        public string D_IndividualAreaQueryBill { get; set; }
        public int D_IndividualAreaOrderFlag { get; set; }
        public string D_BillType { get; set; }
        public int D_State { get; set; }
        public string D_Remark { get; set; }
    }
}
