//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JiGuangLinXin.App.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Core_MallGoods
    {
        public System.Guid G_Id { get; set; }
        public System.Guid G_BusId { get; set; }
        public string G_BusName { get; set; }
        public string G_BusPhone { get; set; }
        public int G_TypeId { get; set; }
        public string G_Name { get; set; }
        public string G_Img { get; set; }
        public string G_ImgTop { get; set; }
        public decimal G_Price { get; set; }
        public decimal G_PriceOld { get; set; }
        public int G_Discount { get; set; }
        public string G_Desc { get; set; }
        public string G_Content { get; set; }
        public decimal G_ExtraFee { get; set; }
        public string G_Tags { get; set; }
        public int G_Store { get; set; }
        public int G_Sales { get; set; }
        public int G_RemainCount { get; set; }
        public int G_Clicks { get; set; }
        public byte[] G_Vesion { get; set; }
        public int G_Recom { get; set; }
        public int G_Top { get; set; }
        public int G_Status { get; set; }
        public System.DateTime G_Time { get; set; }
        public string G_Remark { get; set; }
        public int G_AuditingState { get; set; }
        public Nullable<System.DateTime> G_CheckTime { get; set; }
        public string G_CheckTips { get; set; }
    }
}
