//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JiGuangLinXin.App.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Core_Comments
    {
        public System.Guid C_Id { get; set; }
        public Nullable<int> C_Type { get; set; }
        public System.Guid C_UserId { get; set; }
        public string C_UserName { get; set; }
        public System.Guid C_RefId { get; set; }
        public string C_RefName { get; set; }
        public string C_Content { get; set; }
        public System.Guid C_ProjectId { get; set; }
        public string C_ProjectTitle { get; set; }
        public System.DateTime C_Time { get; set; }
        public int C_State { get; set; }
    }
}
