//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JiGuangLinXin.App.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Core_Ad
    {
        public int A_Id { get; set; }
        public string A_Core { get; set; }
        public int A_Target { get; set; }
        public int A_Type { get; set; }
        public Nullable<System.Guid> A_Building { get; set; }
        public System.DateTime A_STime { get; set; }
        public System.DateTime A_ETime { get; set; }
        public string A_Title { get; set; }
        public string A_Images { get; set; }
        public string A_Url { get; set; }
        public string A_Video { get; set; }
        public System.DateTime A_Time { get; set; }
        public int A_Status { get; set; }
    }
}
