//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JiGuangLinXin.App.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Core_OwnerCardHistory
    {
        public System.Guid O_Id { get; set; }
        public System.Guid O_CodeId { get; set; }
        public string O_Code { get; set; }
        public System.Guid O_UserId { get; set; }
        public string O_UserNickname { get; set; }
        public string O_UserPhone { get; set; }
        public decimal O_Money { get; set; }
        public decimal O_MoneyDiscount { get; set; }
        public int O_Flag { get; set; }
        public System.DateTime O_Time { get; set; }
        public double O_Discount { get; set; }
        public string O_PayOrder { get; set; }
        public int O_Way { get; set; }
    }
}
