//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JiGuangLinXin.App.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Core_VillageLinxin
    {
        public System.Guid V_Id { get; set; }
        public string V_ChatID { get; set; }
        public string V_CityName { get; set; }
        public string V_DistrictName { get; set; }
        public string V_BuildingName { get; set; }
        public int V_BuildingCells { get; set; }
        public double V_BuildingArea { get; set; }
        public string V_BuildingAddress { get; set; }
        public string V_Architecture { get; set; }
        public string V_Property { get; set; }
        public string V_Developers { get; set; }
        public double V_CoordX { get; set; }
        public double V_CoordY { get; set; }
        public int V_Consociation { get; set; }
        public string V_Tags { get; set; }
        public string V_Img { get; set; }
        public int V_Number { get; set; }
        public int V_Hot { get; set; }
        public string V_Remark { get; set; }
        public Nullable<System.DateTime> V_BuildingTime { get; set; }
        public System.DateTime V_Time { get; set; }
        public string V_AreaCode { get; set; }
        public int V_State { get; set; }
    }
}
