//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JiGuangLinXin.App.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Core_MallOrderDetail
    {
        public System.Guid OD_Id { get; set; }
        public string OD_OrderId { get; set; }
        public System.Guid OD_GoodsId { get; set; }
        public System.Guid OD_UId { get; set; }
        public string OD_UPhone { get; set; }
        public System.Guid OD_BusId { get; set; }
        public string OD_BusName { get; set; }
        public string OD_BusPhone { get; set; }
        public string OD_Name { get; set; }
        public string OD_Img { get; set; }
        public decimal OD_Price { get; set; }
        public int OD_Count { get; set; }
        public string OD_Remark { get; set; }
        public System.DateTime OD_Time { get; set; }
    }
}
