//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JiGuangLinXin.App.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Core_VoucherCardHistory
    {
        public System.Guid H_Id { get; set; }
        public System.Guid H_UserId { get; set; }
        public string H_UserNickname { get; set; }
        public string H_UserPhone { get; set; }
        public System.Guid H_BusId { get; set; }
        public string H_Nickname { get; set; }
        public System.Guid H_CardId { get; set; }
        public decimal H_Money { get; set; }
        public System.DateTime H_Time { get; set; }
        public int H_State { get; set; }
        public string H_Title { get; set; }
        public System.DateTime H_STime { get; set; }
        public System.DateTime H_ETime { get; set; }
        public byte[] H_Timestamp { get; set; }
    }
}
