//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JiGuangLinXin.App.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Core_LuckyGiftDetail
    {
        public System.Guid LD_Id { get; set; }
        public System.Guid LD_GiftId { get; set; }
        public decimal LD_Money { get; set; }
        public int LD_Status { get; set; }
        public Nullable<System.Guid> LD_Uid { get; set; }
    }
}
