//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JiGuangLinXin.App.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Core_DeliveryAddress
    {
        public int A_Id { get; set; }
        public System.Guid A_UserId { get; set; }
        public string A_UserName { get; set; }
        public string A_Phone { get; set; }
        public string A_Address { get; set; }
        public string A_Remark { get; set; }
        public int A_State { get; set; }
        public int A_Default { get; set; }
    }
}
