//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JiGuangLinXin.App.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Core_ActivityApply
    {
        public int AA_Id { get; set; }
        public System.Guid AA_ActivityId { get; set; }
        public System.Guid AA_UId { get; set; }
        public string AA_UPhone { get; set; }
        public int AA_Status { get; set; }
        public string AA_Remark { get; set; }
        public System.DateTime AA_Time { get; set; }
    }
}
