//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JiGuangLinXin.App.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Core_Showcase
    {
        public System.Guid S_Id { get; set; }
        public System.Guid S_BusId { get; set; }
        public string S_BusName { get; set; }
        public string S_BusLogo { get; set; }
        public int S_BusRole { get; set; }
        public string S_Phone { get; set; }
        public string S_Title { get; set; }
        public string S_ImgTop { get; set; }
        public int S_Flag { get; set; }
        public string S_Video { get; set; }
        public string S_Img { get; set; }
        public string S_Content { get; set; }
        public string S_Tags { get; set; }
        public Nullable<System.DateTime> S_STime { get; set; }
        public Nullable<System.DateTime> S_ETime { get; set; }
        public string S_Remark { get; set; }
        public int S_Likes { get; set; }
        public int S_Comments { get; set; }
        public int S_Clicks { get; set; }
        public int S_Rank { get; set; }
        public int S_Recom { get; set; }
        public int S_Top { get; set; }
        public int S_Status { get; set; }
        public string S_Desc { get; set; }
        public string S_Address { get; set; }
        public string S_LinkPhone { get; set; }
        public System.DateTime S_Date { get; set; }
        public string S_TargetUrl { get; set; }
        public string S_GoodsName { get; set; }
        public Nullable<System.Guid> S_GoodsId { get; set; }
        public Nullable<System.Guid> S_BuildingId { get; set; }
        public string S_BuildingName { get; set; }
        public int S_Target { get; set; }
        public int S_Hongbao { get; set; }
    }
}
