//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JiGuangLinXin.App.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Core_Score
    {
        public System.Guid S_AccountId { get; set; }
        public int S_Score { get; set; }
        public int S_ForzenScore { get; set; }
        public byte[] S_Vesion { get; set; }
        public string S_PayPwd { get; set; }
        public string S_EncryptCode { get; set; }
        public int S_Role { get; set; }
        public string S_Remark { get; set; }
    }
}
