//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JiGuangLinXin.App.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Core_BusinessEnteringApply
    {
        public int BA_Id { get; set; }
        public System.Guid BA_BusId { get; set; }
        public string BA_NickName { get; set; }
        public int BA_Category { get; set; }
        public string BA_City { get; set; }
        public string BA_Address { get; set; }
        public string BA_AreaCode { get; set; }
        public string BA_BuildingName { get; set; }
        public string BA_Logo { get; set; }
        public string BA_CardImg { get; set; }
        public string BA_BusLicenseImg { get; set; }
        public string BA_OrganizationCodeImg { get; set; }
        public int BA_State { get; set; }
        public System.DateTime BA_Time { get; set; }
        public Nullable<System.DateTime> BA_CheckTime { get; set; }
        public string BA_CheckTips { get; set; }
        public string BA_Remark { get; set; }
        public string BA_Phone { get; set; }
        public string BA_TrueName { get; set; }
        public string BA_CardId { get; set; }
    }
}
