//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JiGuangLinXin.App.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Core_Topic
    {
        public System.Guid T_Id { get; set; }
        public System.Guid T_UserId { get; set; }
        public string T_Title { get; set; }
        public int T_Typle { get; set; }
        public int T_Hongbao { get; set; }
        public int T_Ticket { get; set; }
        public string T_Img { get; set; }
        public int T_ImgAttaCount { get; set; }
        public string T_Tags { get; set; }
        public string T_Remark { get; set; }
        public int T_Clicks { get; set; }
        public int T_Likes { get; set; }
        public int T_Comments { get; set; }
        public int T_Recom { get; set; }
        public int T_Top { get; set; }
        public int T_Status { get; set; }
        public string T_AreaCode { get; set; }
        public System.Guid T_VillageId { get; set; }
        public System.DateTime T_Date { get; set; }
    }
}
