//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JiGuangLinXin.App.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Core_LifestyleServicesLike
    {
        public int L_Id { get; set; }
        public System.Guid L_UserId { get; set; }
        public string L_UserName { get; set; }
        public System.Guid L_ServiceId { get; set; }
        public string L_ServiceName { get; set; }
        public string L_ServiceImg { get; set; }
        public System.DateTime L_Time { get; set; }
        public int L_State { get; set; }
    }
}
