//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JiGuangLinXin.App.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Core_Event
    {
        public System.Guid E_Id { get; set; }
        public System.Guid E_BusId { get; set; }
        public string E_BusName { get; set; }
        public int E_BusRole { get; set; }
        public string E_Title { get; set; }
        public string E_ImgTop { get; set; }
        public int E_Flag { get; set; }
        public string E_Video { get; set; }
        public string E_Img { get; set; }
        public string E_Content { get; set; }
        public string E_Tags { get; set; }
        public Nullable<System.DateTime> E_STime { get; set; }
        public Nullable<System.DateTime> E_ETime { get; set; }
        public int E_ControlValue { get; set; }
        public int E_ControlValueFlag { get; set; }
        public string E_Remark { get; set; }
        public int E_Likes { get; set; }
        public int E_Comments { get; set; }
        public int E_Clicks { get; set; }
        public int E_Rank { get; set; }
        public int E_Recom { get; set; }
        public int E_Top { get; set; }
        public int E_Status { get; set; }
        public string E_Desc { get; set; }
        public string E_Address { get; set; }
        public string E_LinkPhone { get; set; }
        public System.DateTime E_Date { get; set; }
        public Nullable<int> E_IsSelectedOne { get; set; }
        public string E_TargetUrl { get; set; }
        public string E_GoodsName { get; set; }
        public Nullable<System.Guid> E_GoodsId { get; set; }
        public int E_Target { get; set; }
        public int E_AuditingState { get; set; }
        public Nullable<System.DateTime> E_CheckTime { get; set; }
        public string E_CheckTips { get; set; }
    }
}
