//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JiGuangLinXin.App.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Core_Hotline
    {
        public int H_Id { get; set; }
        public System.Guid H_BuildingId { get; set; }
        public string H_BuildingName { get; set; }
        public int H_Flag { get; set; }
        public int H_Rank { get; set; }
        public string H_Phone { get; set; }
        public System.Guid H_UId { get; set; }
        public string H_UPhone { get; set; }
        public string H_NickName { get; set; }
        public System.DateTime H_Time { get; set; }
        public string H_Title { get; set; }
    }
}
