//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JiGuangLinXin.App.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LinXinApp20Entities : DbContext
    {
        public LinXinApp20Entities()
            : base("name=LinXinApp20Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Core_Activity> Core_Activity { get; set; }
        public virtual DbSet<Core_ActivityApply> Core_ActivityApply { get; set; }
        public virtual DbSet<Core_ActivityGoods> Core_ActivityGoods { get; set; }
        public virtual DbSet<Core_ActivityGoodsOrder> Core_ActivityGoodsOrder { get; set; }
        public virtual DbSet<Core_Ad> Core_Ad { get; set; }
        public virtual DbSet<Core_AlipayOrder> Core_AlipayOrder { get; set; }
        public virtual DbSet<Core_AuditingCash> Core_AuditingCash { get; set; }
        public virtual DbSet<Core_AuditingGroupMananger> Core_AuditingGroupMananger { get; set; }
        public virtual DbSet<Core_AuditingVillage> Core_AuditingVillage { get; set; }
        public virtual DbSet<Core_Balance> Core_Balance { get; set; }
        public virtual DbSet<Core_BillMember> Core_BillMember { get; set; }
        public virtual DbSet<Core_BuidingCube> Core_BuidingCube { get; set; }
        public virtual DbSet<Core_Building> Core_Building { get; set; }
        public virtual DbSet<Core_BuildingActivity> Core_BuildingActivity { get; set; }
        public virtual DbSet<Core_BuildingType> Core_BuildingType { get; set; }
        public virtual DbSet<Core_BusDeveloper> Core_BusDeveloper { get; set; }
        public virtual DbSet<Core_Business> Core_Business { get; set; }
        public virtual DbSet<Core_BusinessEnteringApply> Core_BusinessEnteringApply { get; set; }
        public virtual DbSet<Core_BusinessVillage> Core_BusinessVillage { get; set; }
        public virtual DbSet<Core_ChinapayDept> Core_ChinapayDept { get; set; }
        public virtual DbSet<Core_ChinapayOrder> Core_ChinapayOrder { get; set; }
        public virtual DbSet<Core_ChinapayOrder_bk> Core_ChinapayOrder_bk { get; set; }
        public virtual DbSet<Core_DeliveryAddress> Core_DeliveryAddress { get; set; }
        public virtual DbSet<Core_Event> Core_Event { get; set; }
        public virtual DbSet<Core_EventApply> Core_EventApply { get; set; }
        public virtual DbSet<Core_EventGatherLike> Core_EventGatherLike { get; set; }
        public virtual DbSet<Core_EventJoinHistory> Core_EventJoinHistory { get; set; }
        public virtual DbSet<Core_EventScope> Core_EventScope { get; set; }
        public virtual DbSet<Core_EventVoteItem> Core_EventVoteItem { get; set; }
        public virtual DbSet<Core_GroupAlbum> Core_GroupAlbum { get; set; }
        public virtual DbSet<Core_GroupAlbumPic> Core_GroupAlbumPic { get; set; }
        public virtual DbSet<Core_GroupBuyOrder> Core_GroupBuyOrder { get; set; }
        public virtual DbSet<Core_GroupBuyVillage> Core_GroupBuyVillage { get; set; }
        public virtual DbSet<Core_Interactive> Core_Interactive { get; set; }
        public virtual DbSet<Core_Invite> Core_Invite { get; set; }
        public virtual DbSet<Core_InviteApply> Core_InviteApply { get; set; }
        public virtual DbSet<Core_InviteGroup> Core_InviteGroup { get; set; }
        public virtual DbSet<Core_InviteReply> Core_InviteReply { get; set; }
        public virtual DbSet<Core_JuheDept> Core_JuheDept { get; set; }
        public virtual DbSet<Core_JuheOrder> Core_JuheOrder { get; set; }
        public virtual DbSet<Core_LifestyleServicesLike> Core_LifestyleServicesLike { get; set; }
        public virtual DbSet<Core_LifestyleType> Core_LifestyleType { get; set; }
        public virtual DbSet<Core_Likes> Core_Likes { get; set; }
        public virtual DbSet<Core_LuckyGift> Core_LuckyGift { get; set; }
        public virtual DbSet<Core_LuckyGiftBackOrder> Core_LuckyGiftBackOrder { get; set; }
        public virtual DbSet<Core_LuckyGiftDetail> Core_LuckyGiftDetail { get; set; }
        public virtual DbSet<Core_LuckyGiftHistory> Core_LuckyGiftHistory { get; set; }
        public virtual DbSet<Core_MallGoods> Core_MallGoods { get; set; }
        public virtual DbSet<Core_MallOrder> Core_MallOrder { get; set; }
        public virtual DbSet<Core_MallOrderDetail> Core_MallOrderDetail { get; set; }
        public virtual DbSet<Core_MallType> Core_MallType { get; set; }
        public virtual DbSet<Core_MalShoppingCar> Core_MalShoppingCar { get; set; }
        public virtual DbSet<Core_OwnerCardHistory> Core_OwnerCardHistory { get; set; }
        public virtual DbSet<Core_Showcase> Core_Showcase { get; set; }
        public virtual DbSet<Core_ShowcaseScope> Core_ShowcaseScope { get; set; }
        public virtual DbSet<Core_Topic> Core_Topic { get; set; }
        public virtual DbSet<Core_TopicMovieTicket> Core_TopicMovieTicket { get; set; }
        public virtual DbSet<Core_User> Core_User { get; set; }
        public virtual DbSet<Core_UserFriend> Core_UserFriend { get; set; }
        public virtual DbSet<Core_UserFriendsApply> Core_UserFriendsApply { get; set; }
        public virtual DbSet<Core_Village> Core_Village { get; set; }
        public virtual DbSet<Core_VillageLinxin> Core_VillageLinxin { get; set; }
        public virtual DbSet<Core_VoucherCard> Core_VoucherCard { get; set; }
        public virtual DbSet<Core_VoucherCardHistory> Core_VoucherCardHistory { get; set; }
        public virtual DbSet<Core_VoucherCardPost> Core_VoucherCardPost { get; set; }
        public virtual DbSet<Sys_Admin> Sys_Admin { get; set; }
        public virtual DbSet<Sys_AdSystem> Sys_AdSystem { get; set; }
        public virtual DbSet<Sys_Attachment> Sys_Attachment { get; set; }
        public virtual DbSet<Sys_BaseInfo> Sys_BaseInfo { get; set; }
        public virtual DbSet<Sys_BillMaster> Sys_BillMaster { get; set; }
        public virtual DbSet<Sys_CheckHistory> Sys_CheckHistory { get; set; }
        public virtual DbSet<Sys_City> Sys_City { get; set; }
        public virtual DbSet<Sys_DbErrorLog> Sys_DbErrorLog { get; set; }
        public virtual DbSet<Sys_DiscountRate> Sys_DiscountRate { get; set; }
        public virtual DbSet<Sys_District> Sys_District { get; set; }
        public virtual DbSet<Sys_ErrorLog> Sys_ErrorLog { get; set; }
        public virtual DbSet<Sys_IndexRecommend> Sys_IndexRecommend { get; set; }
        public virtual DbSet<Sys_Message> Sys_Message { get; set; }
        public virtual DbSet<Sys_MessageCenter> Sys_MessageCenter { get; set; }
        public virtual DbSet<Sys_OperateLog> Sys_OperateLog { get; set; }
        public virtual DbSet<Sys_OwnerCard> Sys_OwnerCard { get; set; }
        public virtual DbSet<Sys_Province> Sys_Province { get; set; }
        public virtual DbSet<Core_LifestyleOrder> Core_LifestyleOrder { get; set; }
        public virtual DbSet<Core_LifestyleServices> Core_LifestyleServices { get; set; }
        public virtual DbSet<view_businessService> view_businessService { get; set; }
        public virtual DbSet<view_event> view_event { get; set; }
        public virtual DbSet<view_receiveGiftList> view_receiveGiftList { get; set; }
        public virtual DbSet<view_shoppingCar> view_shoppingCar { get; set; }
        public virtual DbSet<view_topicTicketHistory> view_topicTicketHistory { get; set; }
        public virtual DbSet<view_topicTicketReceive> view_topicTicketReceive { get; set; }
        public virtual DbSet<view_topicTicketSend> view_topicTicketSend { get; set; }
        public virtual DbSet<Sys_AppVersion> Sys_AppVersion { get; set; }
        public virtual DbSet<Core_GroupBuyType> Core_GroupBuyType { get; set; }
        public virtual DbSet<Core_GroupBuy> Core_GroupBuy { get; set; }
        public virtual DbSet<Core_GroupBuyScope> Core_GroupBuyScope { get; set; }
        public virtual DbSet<Core_Feedback> Core_Feedback { get; set; }
        public virtual DbSet<Sys_JPushMessage> Sys_JPushMessage { get; set; }
        public virtual DbSet<Sys_OwnerCardCode> Sys_OwnerCardCode { get; set; }
        public virtual DbSet<Core_Comments> Core_Comments { get; set; }
        public virtual DbSet<Core_Prize> Core_Prize { get; set; }
        public virtual DbSet<Core_PrizeDetail> Core_PrizeDetail { get; set; }
        public virtual DbSet<Core_Billboard> Core_Billboard { get; set; }
        public virtual DbSet<Core_Hotline> Core_Hotline { get; set; }
        public virtual DbSet<Core_Score> Core_Score { get; set; }
        public virtual DbSet<Core_ScoreHistory> Core_ScoreHistory { get; set; }
        public virtual DbSet<Core_ScoreExchange> Core_ScoreExchange { get; set; }
        public virtual DbSet<Sys_Notice> Sys_Notice { get; set; }
    }
}
