//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JiGuangLinXin.App.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_Message
    {
        public int M_Id { get; set; }
        public int M_Type { get; set; }
        public int M_Flag { get; set; }
        public string M_TargetId { get; set; }
        public string M_Title { get; set; }
        public string M_Content { get; set; }
        public string M_ShowModal { get; set; }
        public System.DateTime M_Time { get; set; }
    }
}
