//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JiGuangLinXin.App.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_OwnerCardCode
    {
        public System.Guid C_Id { get; set; }
        public System.Guid C_PId { get; set; }
        public string C_Code { get; set; }
        public decimal C_Money { get; set; }
        public string C_BatchNo { get; set; }
        public Nullable<System.DateTime> C_Time { get; set; }
        public Nullable<System.DateTime> C_ActiveTime { get; set; }
        public int C_State { get; set; }
        public string C_Remark { get; set; }
        public int C_Flag { get; set; }
    }
}
