//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JiGuangLinXin.App.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_IndexRecommend
    {
        public System.Guid R_Id { get; set; }
        public System.Guid R_BusId { get; set; }
        public string R_BusName { get; set; }
        public string R_BusPhone { get; set; }
        public System.Guid R_ProId { get; set; }
        public string R_ProName { get; set; }
        public string R_Tags { get; set; }
        public string R_Titlte { get; set; }
        public int R_Target { get; set; }
        public string R_ImgUrl { get; set; }
        public int R_State { get; set; }
        public int R_Type { get; set; }
        public string R_Remark { get; set; }
        public int R_Rank { get; set; }
        public System.DateTime R_STime { get; set; }
        public System.DateTime R_ETime { get; set; }
        public System.DateTime R_Time { get; set; }
        public System.Guid R_AdminId { get; set; }
        public string R_AdminName { get; set; }
    }
}
