//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JiGuangLinXin.App.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_CheckHistory
    {
        public int H_Id { get; set; }
        public System.Guid H_AdminId { get; set; }
        public string H_AdminName { get; set; }
        public string H_ProId { get; set; }
        public string H_ProName { get; set; }
        public int H_Flag { get; set; }
        public System.DateTime H_Time { get; set; }
        public int H_CheckState { get; set; }
        public int H_State { get; set; }
        public string H_Tips { get; set; }
        public int H_Role { get; set; }
    }
}
