//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JiGuangLinXin.App.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_DbErrorLog
    {
        public int errorLogID { get; set; }
        public Nullable<System.DateTime> errorTime { get; set; }
        public string userName { get; set; }
        public Nullable<int> errorNumber { get; set; }
        public Nullable<int> errorSeverity { get; set; }
        public Nullable<int> errorState { get; set; }
        public string errorProcedure { get; set; }
        public Nullable<int> errorLine { get; set; }
        public string errorMessage { get; set; }
    }
}
