//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JiGuangLinXin.App.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_Notice
    {
        public int N_Id { get; set; }
        public string N_Title { get; set; }
        public string N_SubTitle { get; set; }
        public string N_Content { get; set; }
        public int N_Flag { get; set; }
        public string N_Tags { get; set; }
        public int N_Clicks { get; set; }
        public string N_Attach { get; set; }
        public string N_Remark { get; set; }
        public System.DateTime N_Date { get; set; }
        public string N_AreaCode { get; set; }
        public System.Guid N_VillageId { get; set; }
        public int N_State { get; set; }
    }
}
