//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JiGuangLinXin.App.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_OwnerCard
    {
        public System.Guid OC_Id { get; set; }
        public int OC_Flag { get; set; }
        public decimal OC_Money { get; set; }
        public string OC_BatchNo { get; set; }
        public Nullable<System.DateTime> OC_Time { get; set; }
        public int OC_TotalCount { get; set; }
        public int OC_RemainCount { get; set; }
        public string OC_Remark { get; set; }
        public System.Guid OC_AdminId { get; set; }
        public string OC_AdminName { get; set; }
        public byte[] OC_Timestamp { get; set; }
    }
}
