//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JiGuangLinXin.App.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_AdSystem
    {
        public int A_Id { get; set; }
        public int A_Place { get; set; }
        public int A_Target { get; set; }
        public int A_Type { get; set; }
        public string A_Building { get; set; }
        public System.DateTime A_STime { get; set; }
        public System.DateTime A_ETime { get; set; }
        public string A_Title { get; set; }
        public string A_ImgUrl { get; set; }
        public string A_Desc { get; set; }
        public string A_Linkurl { get; set; }
        public System.DateTime A_Time { get; set; }
        public int A_Status { get; set; }
        public System.Guid A_BusId { get; set; }
        public string A_BusName { get; set; }
        public int A_BusRole { get; set; }
        public string A_Phone { get; set; }
        public string A_Tags { get; set; }
        public string A_Remark { get; set; }
        public int A_Clicks { get; set; }
        public string A_ProjectName { get; set; }
        public Nullable<System.Guid> A_ProjectId { get; set; }
    }
}
