//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JiGuangLinXin.App.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_BaseInfo
    {
        public int B_Id { get; set; }
        public string B_Code { get; set; }
        public string B_Title { get; set; }
        public string B_SubTitle { get; set; }
        public string B_Content { get; set; }
        public System.DateTime B_Time { get; set; }
        public string B_ExProp { get; set; }
    }
}
