//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JiGuangLinXin.App.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_ErrorLog
    {
        public int L_Id { get; set; }
        public int L_DriverType { get; set; }
        public string L_Phone { get; set; }
        public System.Guid L_UId { get; set; }
        public string L_Url { get; set; }
        public int L_Flag { get; set; }
        public string L_Desc { get; set; }
        public System.DateTime L_Time { get; set; }
    }
}
