//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JiGuangLinXin.App.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_event
    {
        public System.Guid E_Id { get; set; }
        public System.Guid E_BusId { get; set; }
        public string E_Title { get; set; }
        public string E_Tags { get; set; }
        public string E_Img { get; set; }
        public string E_Video { get; set; }
        public int E_Top { get; set; }
        public int E_Clicks { get; set; }
        public int E_Comments { get; set; }
        public int E_Likes { get; set; }
        public System.DateTime E_Date { get; set; }
        public string B_NickName { get; set; }
        public string B_Logo { get; set; }
        public string B_City { get; set; }
        public string B_Address { get; set; }
        public System.Guid BuildingId { get; set; }
        public int E_BusRole { get; set; }
        public int E_Rank { get; set; }
    }
}
