//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JiGuangLinXin.App.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_receiveGiftList
    {
        public System.Guid giftId { get; set; }
        public int giftType { get; set; }
        public System.Guid userSendId { get; set; }
        public string userSendNickName { get; set; }
        public string userReceiveNickname { get; set; }
        public System.Guid userReceiveId { get; set; }
        public string giftTitle { get; set; }
        public string giftTips { get; set; }
        public decimal money { get; set; }
        public System.DateTime createTime { get; set; }
    }
}
