//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JiGuangLinXin.App.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_businessService
    {
        public System.Guid busId { get; set; }
        public string nickname { get; set; }
        public string logo { get; set; }
        public string coverImg { get; set; }
        public int categoryId { get; set; }
        public System.Guid buildingId { get; set; }
    }
}
