//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JiGuangLinXin.App.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_shoppingCar
    {
        public int S_Id { get; set; }
        public System.Guid S_BusId { get; set; }
        public System.Guid S_UId { get; set; }
        public System.Guid S_GoodsId { get; set; }
        public System.DateTime S_Time { get; set; }
        public int S_GoodsCount { get; set; }
        public string S_Remark { get; set; }
        public int G_Status { get; set; }
        public string G_Name { get; set; }
        public decimal G_Price { get; set; }
        public string G_Img { get; set; }
        public decimal G_ExtraFee { get; set; }
        public string B_NickName { get; set; }
        public string B_Phone { get; set; }
    }
}
