//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JiguangLinXin.App.SpecialEvent.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Core_Statistics
    {
        public int S_Id { get; set; }
        public int S_Votes { get; set; }
        public int S_VillageCount { get; set; }
        public int S_Views { get; set; }
        public string S_Remark { get; set; }
        public byte[] S_Timestamp { get; set; }
    }
}
