//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JiguangLinXin.App.SpecialEvent.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Core_VillageApply
    {
        public System.Guid A_Id { get; set; }
        public string A_WeixinNo { get; set; }
        public string A_WeixinLogo { get; set; }
        public string A_ApplyName { get; set; }
        public string A_CityName { get; set; }
        public string A_DistrictName { get; set; }
        public System.DateTime A_Time { get; set; }
        public int A_State { get; set; }
    }
}
