//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JiguangLinXin.App.SpecialEvent.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Core_VillageVote
    {
        public System.Guid C_Id { get; set; }
        public System.Guid C_BuildingId { get; set; }
        public string C_WeixinNo { get; set; }
        public string C_WeixinLogo { get; set; }
        public System.DateTime C_Time { get; set; }
        public string C_Ip { get; set; }
        public int C_Source { get; set; }
    }
}
