//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JiguangLinXin.App.SpecialEvent.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SpecialEventEntities : DbContext
    {
        public SpecialEventEntities()
            : base("name=SpecialEventEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Core_Village> Core_Village { get; set; }
        public virtual DbSet<Core_VillageApply> Core_VillageApply { get; set; }
        public virtual DbSet<Core_VillageVote> Core_VillageVote { get; set; }
        public virtual DbSet<Sys_Admin> Sys_Admin { get; set; }
        public virtual DbSet<Core_Statistics> Core_Statistics { get; set; }
        public virtual DbSet<Sys_City> Sys_City { get; set; }
        public virtual DbSet<Sys_District> Sys_District { get; set; }
        public virtual DbSet<Sys_Province> Sys_Province { get; set; }
        public virtual DbSet<Core_History> Core_History { get; set; }
    }
}
