//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JiguangLinXin.App.SpecialEvent.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_District
    {
        public int D_PK_ID { get; set; }
        public int D_CityID { get; set; }
        public string D_Name { get; set; }
        public string D_PostCode { get; set; }
        public string D_LevelCode { get; set; }
        public Nullable<int> D_Sort { get; set; }
        public string D_Pinyin { get; set; }
    }
}
