//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JiguangLinXin.App.SpecialEvent.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_Province
    {
        public int P_PK_ID { get; set; }
        public string P_Name { get; set; }
        public string P_LevelCode { get; set; }
        public int P_Sort { get; set; }
        public string P_Pinyin { get; set; }
    }
}
